name: Deploy pythonanywhere webapp
# Configura servidor de CI para executar o pipeline de tarefas abaixo (jobs) quando 
# um push ou pull request for realizado tendo como alvo a branch main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Reload webapp
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'
          username: 'ricardojob'
          api-token: 'b61838971c2ac3be84ff663bd1e0bc523c29d1f6'
          domain-name: 'user.pythonanywhere.com'